<?php
/**
 * AddressBookApi
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\cargoInternational
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spedition.de - Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\cargoInternational\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use kruegge82\cargoInternational\ApiException;
use kruegge82\cargoInternational\Configuration;
use kruegge82\cargoInternational\FormDataProcessor;
use kruegge82\cargoInternational\HeaderSelector;
use kruegge82\cargoInternational\ObjectSerializer;

/**
 * AddressBookApi Class Doc Comment
 *
 * @category Class
 * @package  kruegge82\cargoInternational
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddressBookApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createAddressbook' => [
            'application/x-www-form-urlencoded',
        ],
        'deleteAddressbook' => [
            'application/json',
        ],
        'destroyAddressbook' => [
            'application/json',
        ],
        'getAddressbook' => [
            'application/json',
        ],
        'listAddressbook' => [
            'application/json',
        ],
        'listTrashedAddressbook' => [
            'application/json',
        ],
        'restoreAddressbook' => [
            'application/json',
        ],
        'updateAddressbook' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createAddressbook
     *
     * Store new record
     *
     * @param  string $firstname The first name (required)
     * @param  string $lastname The last name (required)
     * @param  string $street Street &amp; House number (required)
     * @param  string $zip Zipcode (required)
     * @param  string $city City (required)
     * @param  string $country The 2 letter country code (required)
     * @param  string $phone Phone number (required)
     * @param  string $email E-Mail address (required)
     * @param  string|null $company Company name (optional)
     * @param  string|null $department Department name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function createAddressbook($firstname, $lastname, $street, $zip, $city, $country, $phone, $email, $company = null, $department = null, string $contentType = self::contentTypes['createAddressbook'][0])
    {
        $this->createAddressbookWithHttpInfo($firstname, $lastname, $street, $zip, $city, $country, $phone, $email, $company, $department, $contentType);
    }

    /**
     * Operation createAddressbookWithHttpInfo
     *
     * Store new record
     *
     * @param  string $firstname The first name (required)
     * @param  string $lastname The last name (required)
     * @param  string $street Street &amp; House number (required)
     * @param  string $zip Zipcode (required)
     * @param  string $city City (required)
     * @param  string $country The 2 letter country code (required)
     * @param  string $phone Phone number (required)
     * @param  string $email E-Mail address (required)
     * @param  string|null $company Company name (optional)
     * @param  string|null $department Department name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function createAddressbookWithHttpInfo($firstname, $lastname, $street, $zip, $city, $country, $phone, $email, $company = null, $department = null, string $contentType = self::contentTypes['createAddressbook'][0])
    {
        $request = $this->createAddressbookRequest($firstname, $lastname, $street, $zip, $city, $country, $phone, $email, $company, $department, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation createAddressbookAsync
     *
     * Store new record
     *
     * @param  string $firstname The first name (required)
     * @param  string $lastname The last name (required)
     * @param  string $street Street &amp; House number (required)
     * @param  string $zip Zipcode (required)
     * @param  string $city City (required)
     * @param  string $country The 2 letter country code (required)
     * @param  string $phone Phone number (required)
     * @param  string $email E-Mail address (required)
     * @param  string|null $company Company name (optional)
     * @param  string|null $department Department name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAddressbookAsync($firstname, $lastname, $street, $zip, $city, $country, $phone, $email, $company = null, $department = null, string $contentType = self::contentTypes['createAddressbook'][0])
    {
        return $this->createAddressbookAsyncWithHttpInfo($firstname, $lastname, $street, $zip, $city, $country, $phone, $email, $company, $department, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createAddressbookAsyncWithHttpInfo
     *
     * Store new record
     *
     * @param  string $firstname The first name (required)
     * @param  string $lastname The last name (required)
     * @param  string $street Street &amp; House number (required)
     * @param  string $zip Zipcode (required)
     * @param  string $city City (required)
     * @param  string $country The 2 letter country code (required)
     * @param  string $phone Phone number (required)
     * @param  string $email E-Mail address (required)
     * @param  string|null $company Company name (optional)
     * @param  string|null $department Department name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAddressbookAsyncWithHttpInfo($firstname, $lastname, $street, $zip, $city, $country, $phone, $email, $company = null, $department = null, string $contentType = self::contentTypes['createAddressbook'][0])
    {
        $returnType = '';
        $request = $this->createAddressbookRequest($firstname, $lastname, $street, $zip, $city, $country, $phone, $email, $company, $department, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createAddressbook'
     *
     * @param  string $firstname The first name (required)
     * @param  string $lastname The last name (required)
     * @param  string $street Street &amp; House number (required)
     * @param  string $zip Zipcode (required)
     * @param  string $city City (required)
     * @param  string $country The 2 letter country code (required)
     * @param  string $phone Phone number (required)
     * @param  string $email E-Mail address (required)
     * @param  string|null $company Company name (optional)
     * @param  string|null $department Department name (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createAddressbookRequest($firstname, $lastname, $street, $zip, $city, $country, $phone, $email, $company = null, $department = null, string $contentType = self::contentTypes['createAddressbook'][0])
    {

        // verify the required parameter 'firstname' is set
        if ($firstname === null || (is_array($firstname) && count($firstname) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $firstname when calling createAddressbook'
            );
        }
        if (strlen($firstname) > 2) {
            throw new \InvalidArgumentException('invalid length for "$firstname" when calling AddressBookApi.createAddressbook, must be smaller than or equal to 2.');
        }
        
        // verify the required parameter 'lastname' is set
        if ($lastname === null || (is_array($lastname) && count($lastname) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $lastname when calling createAddressbook'
            );
        }

        // verify the required parameter 'street' is set
        if ($street === null || (is_array($street) && count($street) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $street when calling createAddressbook'
            );
        }

        // verify the required parameter 'zip' is set
        if ($zip === null || (is_array($zip) && count($zip) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $zip when calling createAddressbook'
            );
        }

        // verify the required parameter 'city' is set
        if ($city === null || (is_array($city) && count($city) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $city when calling createAddressbook'
            );
        }

        // verify the required parameter 'country' is set
        if ($country === null || (is_array($country) && count($country) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $country when calling createAddressbook'
            );
        }

        // verify the required parameter 'phone' is set
        if ($phone === null || (is_array($phone) && count($phone) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $phone when calling createAddressbook'
            );
        }

        // verify the required parameter 'email' is set
        if ($email === null || (is_array($email) && count($email) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $email when calling createAddressbook'
            );
        }




        $resourcePath = '/api/addressbook/create';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'firstname' => $firstname,
            'lastname' => $lastname,
            'company' => $company,
            'department' => $department,
            'street' => $street,
            'zip' => $zip,
            'city' => $city,
            'country' => $country,
            'phone' => $phone,
            'email' => $email,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteAddressbook
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return object|object
     */
    public function deleteAddressbook($id, string $contentType = self::contentTypes['deleteAddressbook'][0])
    {
        list($response) = $this->deleteAddressbookWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation deleteAddressbookWithHttpInfo
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of object|object, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteAddressbookWithHttpInfo($id, string $contentType = self::contentTypes['deleteAddressbook'][0])
    {
        $request = $this->deleteAddressbookRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'object',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteAddressbookAsync
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAddressbookAsync($id, string $contentType = self::contentTypes['deleteAddressbook'][0])
    {
        return $this->deleteAddressbookAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteAddressbookAsyncWithHttpInfo
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAddressbookAsyncWithHttpInfo($id, string $contentType = self::contentTypes['deleteAddressbook'][0])
    {
        $returnType = 'object';
        $request = $this->deleteAddressbookRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteAddressbook'
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteAddressbookRequest($id, string $contentType = self::contentTypes['deleteAddressbook'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling deleteAddressbook'
            );
        }


        $resourcePath = '/api/addressbook/delete/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation destroyAddressbook
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['destroyAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return object|object
     */
    public function destroyAddressbook($id, string $contentType = self::contentTypes['destroyAddressbook'][0])
    {
        list($response) = $this->destroyAddressbookWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation destroyAddressbookWithHttpInfo
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['destroyAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of object|object, HTTP status code, HTTP response headers (array of strings)
     */
    public function destroyAddressbookWithHttpInfo($id, string $contentType = self::contentTypes['destroyAddressbook'][0])
    {
        $request = $this->destroyAddressbookRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'object',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation destroyAddressbookAsync
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['destroyAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function destroyAddressbookAsync($id, string $contentType = self::contentTypes['destroyAddressbook'][0])
    {
        return $this->destroyAddressbookAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation destroyAddressbookAsyncWithHttpInfo
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['destroyAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function destroyAddressbookAsyncWithHttpInfo($id, string $contentType = self::contentTypes['destroyAddressbook'][0])
    {
        $returnType = 'object';
        $request = $this->destroyAddressbookRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'destroyAddressbook'
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['destroyAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function destroyAddressbookRequest($id, string $contentType = self::contentTypes['destroyAddressbook'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling destroyAddressbook'
            );
        }


        $resourcePath = '/api/addressbook/destroy/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAddressbook
     *
     * @param  int $id Display specific record id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function getAddressbook($id, string $contentType = self::contentTypes['getAddressbook'][0])
    {
        $this->getAddressbookWithHttpInfo($id, $contentType);
    }

    /**
     * Operation getAddressbookWithHttpInfo
     *
     * @param  int $id Display specific record id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAddressbookWithHttpInfo($id, string $contentType = self::contentTypes['getAddressbook'][0])
    {
        $request = $this->getAddressbookRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAddressbookAsync
     *
     * @param  int $id Display specific record id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAddressbookAsync($id, string $contentType = self::contentTypes['getAddressbook'][0])
    {
        return $this->getAddressbookAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAddressbookAsyncWithHttpInfo
     *
     * @param  int $id Display specific record id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAddressbookAsyncWithHttpInfo($id, string $contentType = self::contentTypes['getAddressbook'][0])
    {
        $returnType = '';
        $request = $this->getAddressbookRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAddressbook'
     *
     * @param  int $id Display specific record id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAddressbookRequest($id, string $contentType = self::contentTypes['getAddressbook'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getAddressbook'
            );
        }


        $resourcePath = '/api/addressbook/details/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listAddressbook
     *
     * List records with pagination
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function listAddressbook($per_page = null, $page = null, string $contentType = self::contentTypes['listAddressbook'][0])
    {
        $this->listAddressbookWithHttpInfo($per_page, $page, $contentType);
    }

    /**
     * Operation listAddressbookWithHttpInfo
     *
     * List records with pagination
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function listAddressbookWithHttpInfo($per_page = null, $page = null, string $contentType = self::contentTypes['listAddressbook'][0])
    {
        $request = $this->listAddressbookRequest($per_page, $page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation listAddressbookAsync
     *
     * List records with pagination
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAddressbookAsync($per_page = null, $page = null, string $contentType = self::contentTypes['listAddressbook'][0])
    {
        return $this->listAddressbookAsyncWithHttpInfo($per_page, $page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listAddressbookAsyncWithHttpInfo
     *
     * List records with pagination
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAddressbookAsyncWithHttpInfo($per_page = null, $page = null, string $contentType = self::contentTypes['listAddressbook'][0])
    {
        $returnType = '';
        $request = $this->listAddressbookRequest($per_page, $page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listAddressbook'
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listAddressbookRequest($per_page = null, $page = null, string $contentType = self::contentTypes['listAddressbook'][0])
    {




        $resourcePath = '/api/addressbook/index';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listTrashedAddressbook
     *
     * List records with pagination
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTrashedAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function listTrashedAddressbook($per_page = null, $page = null, string $contentType = self::contentTypes['listTrashedAddressbook'][0])
    {
        $this->listTrashedAddressbookWithHttpInfo($per_page, $page, $contentType);
    }

    /**
     * Operation listTrashedAddressbookWithHttpInfo
     *
     * List records with pagination
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTrashedAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function listTrashedAddressbookWithHttpInfo($per_page = null, $page = null, string $contentType = self::contentTypes['listTrashedAddressbook'][0])
    {
        $request = $this->listTrashedAddressbookRequest($per_page, $page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation listTrashedAddressbookAsync
     *
     * List records with pagination
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTrashedAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listTrashedAddressbookAsync($per_page = null, $page = null, string $contentType = self::contentTypes['listTrashedAddressbook'][0])
    {
        return $this->listTrashedAddressbookAsyncWithHttpInfo($per_page, $page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listTrashedAddressbookAsyncWithHttpInfo
     *
     * List records with pagination
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTrashedAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listTrashedAddressbookAsyncWithHttpInfo($per_page = null, $page = null, string $contentType = self::contentTypes['listTrashedAddressbook'][0])
    {
        $returnType = '';
        $request = $this->listTrashedAddressbookRequest($per_page, $page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listTrashedAddressbook'
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTrashedAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listTrashedAddressbookRequest($per_page = null, $page = null, string $contentType = self::contentTypes['listTrashedAddressbook'][0])
    {




        $resourcePath = '/api/addressbook/trashed';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation restoreAddressbook
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['restoreAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return object|object
     */
    public function restoreAddressbook($id, string $contentType = self::contentTypes['restoreAddressbook'][0])
    {
        list($response) = $this->restoreAddressbookWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation restoreAddressbookWithHttpInfo
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['restoreAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of object|object, HTTP status code, HTTP response headers (array of strings)
     */
    public function restoreAddressbookWithHttpInfo($id, string $contentType = self::contentTypes['restoreAddressbook'][0])
    {
        $request = $this->restoreAddressbookRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'object',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation restoreAddressbookAsync
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['restoreAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function restoreAddressbookAsync($id, string $contentType = self::contentTypes['restoreAddressbook'][0])
    {
        return $this->restoreAddressbookAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation restoreAddressbookAsyncWithHttpInfo
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['restoreAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function restoreAddressbookAsyncWithHttpInfo($id, string $contentType = self::contentTypes['restoreAddressbook'][0])
    {
        $returnType = 'object';
        $request = $this->restoreAddressbookRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'restoreAddressbook'
     *
     * @param  int $id The ID of the record (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['restoreAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function restoreAddressbookRequest($id, string $contentType = self::contentTypes['restoreAddressbook'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling restoreAddressbook'
            );
        }


        $resourcePath = '/api/addressbook/restore/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateAddressbook
     *
     * @param  int $id The ID of the record (required)
     * @param  \kruegge82\cargoInternational\Model\UpdateAddressbookRequest $update_addressbook_request Data to store (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return object|object
     */
    public function updateAddressbook($id, $update_addressbook_request, string $contentType = self::contentTypes['updateAddressbook'][0])
    {
        list($response) = $this->updateAddressbookWithHttpInfo($id, $update_addressbook_request, $contentType);
        return $response;
    }

    /**
     * Operation updateAddressbookWithHttpInfo
     *
     * @param  int $id The ID of the record (required)
     * @param  \kruegge82\cargoInternational\Model\UpdateAddressbookRequest $update_addressbook_request Data to store (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateAddressbook'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of object|object, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateAddressbookWithHttpInfo($id, $update_addressbook_request, string $contentType = self::contentTypes['updateAddressbook'][0])
    {
        $request = $this->updateAddressbookRequest($id, $update_addressbook_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'object',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation updateAddressbookAsync
     *
     * @param  int $id The ID of the record (required)
     * @param  \kruegge82\cargoInternational\Model\UpdateAddressbookRequest $update_addressbook_request Data to store (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAddressbookAsync($id, $update_addressbook_request, string $contentType = self::contentTypes['updateAddressbook'][0])
    {
        return $this->updateAddressbookAsyncWithHttpInfo($id, $update_addressbook_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateAddressbookAsyncWithHttpInfo
     *
     * @param  int $id The ID of the record (required)
     * @param  \kruegge82\cargoInternational\Model\UpdateAddressbookRequest $update_addressbook_request Data to store (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAddressbookAsyncWithHttpInfo($id, $update_addressbook_request, string $contentType = self::contentTypes['updateAddressbook'][0])
    {
        $returnType = 'object';
        $request = $this->updateAddressbookRequest($id, $update_addressbook_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateAddressbook'
     *
     * @param  int $id The ID of the record (required)
     * @param  \kruegge82\cargoInternational\Model\UpdateAddressbookRequest $update_addressbook_request Data to store (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateAddressbook'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateAddressbookRequest($id, $update_addressbook_request, string $contentType = self::contentTypes['updateAddressbook'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling updateAddressbook'
            );
        }

        // verify the required parameter 'update_addressbook_request' is set
        if ($update_addressbook_request === null || (is_array($update_addressbook_request) && count($update_addressbook_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_addressbook_request when calling updateAddressbook'
            );
        }


        $resourcePath = '/api/addressbook/update/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_addressbook_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_addressbook_request));
            } else {
                $httpBody = $update_addressbook_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
