<?php
/**
 * CarrierTemplatesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\cargoInternational
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spedition.de - Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\cargoInternational\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use kruegge82\cargoInternational\ApiException;
use kruegge82\cargoInternational\Configuration;
use kruegge82\cargoInternational\FormDataProcessor;
use kruegge82\cargoInternational\HeaderSelector;
use kruegge82\cargoInternational\ObjectSerializer;

/**
 * CarrierTemplatesApi Class Doc Comment
 *
 * @category Class
 * @package  kruegge82\cargoInternational
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CarrierTemplatesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'e7854f0669221b6f6a471112b9405f9a' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation e7854f0669221b6f6a471112b9405f9a
     *
     * List records with pagination
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['e7854f0669221b6f6a471112b9405f9a'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function e7854f0669221b6f6a471112b9405f9a($per_page = null, $page = null, string $contentType = self::contentTypes['e7854f0669221b6f6a471112b9405f9a'][0])
    {
        $this->e7854f0669221b6f6a471112b9405f9aWithHttpInfo($per_page, $page, $contentType);
    }

    /**
     * Operation e7854f0669221b6f6a471112b9405f9aWithHttpInfo
     *
     * List records with pagination
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['e7854f0669221b6f6a471112b9405f9a'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoInternational\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function e7854f0669221b6f6a471112b9405f9aWithHttpInfo($per_page = null, $page = null, string $contentType = self::contentTypes['e7854f0669221b6f6a471112b9405f9a'][0])
    {
        $request = $this->e7854f0669221b6f6a471112b9405f9aRequest($per_page, $page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation e7854f0669221b6f6a471112b9405f9aAsync
     *
     * List records with pagination
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['e7854f0669221b6f6a471112b9405f9a'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function e7854f0669221b6f6a471112b9405f9aAsync($per_page = null, $page = null, string $contentType = self::contentTypes['e7854f0669221b6f6a471112b9405f9a'][0])
    {
        return $this->e7854f0669221b6f6a471112b9405f9aAsyncWithHttpInfo($per_page, $page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation e7854f0669221b6f6a471112b9405f9aAsyncWithHttpInfo
     *
     * List records with pagination
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['e7854f0669221b6f6a471112b9405f9a'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function e7854f0669221b6f6a471112b9405f9aAsyncWithHttpInfo($per_page = null, $page = null, string $contentType = self::contentTypes['e7854f0669221b6f6a471112b9405f9a'][0])
    {
        $returnType = '';
        $request = $this->e7854f0669221b6f6a471112b9405f9aRequest($per_page, $page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'e7854f0669221b6f6a471112b9405f9a'
     *
     * @param  int|null $per_page Number of records per page (optional)
     * @param  int|null $page The starting page for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['e7854f0669221b6f6a471112b9405f9a'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function e7854f0669221b6f6a471112b9405f9aRequest($per_page = null, $page = null, string $contentType = self::contentTypes['e7854f0669221b6f6a471112b9405f9a'][0])
    {




        $resourcePath = '/api/templates/carrier/index';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
