<?php
/**
 * CreateOrderRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\cargoInternational
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spedition.de - Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\cargoInternational\Model;

use \ArrayAccess;
use \kruegge82\cargoInternational\ObjectSerializer;

/**
 * CreateOrderRequest Class Doc Comment
 *
 * @category Class
 * @package  kruegge82\cargoInternational
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateOrderRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'createOrder_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'order_number' => 'string',
        'pickup_company' => 'string',
        'pickup_firstname' => 'string',
        'pickup_lastname' => 'string',
        'pickup_street' => 'string',
        'pickup_country' => 'string',
        'pickup_zip' => 'string',
        'pickup_city' => 'string',
        'pickup_phone' => 'string',
        'pickup_email' => 'string',
        'delivery_company' => 'string',
        'delivery_firstname' => 'string',
        'delivery_lastname' => 'string',
        'delivery_street' => 'string',
        'delivery_country' => 'string',
        'delivery_zip' => 'string',
        'delivery_city' => 'string',
        'delivery_phone' => 'string',
        'delivery_email' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'order_number' => null,
        'pickup_company' => null,
        'pickup_firstname' => null,
        'pickup_lastname' => null,
        'pickup_street' => null,
        'pickup_country' => null,
        'pickup_zip' => null,
        'pickup_city' => null,
        'pickup_phone' => null,
        'pickup_email' => null,
        'delivery_company' => null,
        'delivery_firstname' => null,
        'delivery_lastname' => null,
        'delivery_street' => null,
        'delivery_country' => null,
        'delivery_zip' => null,
        'delivery_city' => null,
        'delivery_phone' => null,
        'delivery_email' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'order_number' => false,
        'pickup_company' => false,
        'pickup_firstname' => false,
        'pickup_lastname' => false,
        'pickup_street' => false,
        'pickup_country' => false,
        'pickup_zip' => false,
        'pickup_city' => false,
        'pickup_phone' => false,
        'pickup_email' => false,
        'delivery_company' => false,
        'delivery_firstname' => false,
        'delivery_lastname' => false,
        'delivery_street' => false,
        'delivery_country' => false,
        'delivery_zip' => false,
        'delivery_city' => false,
        'delivery_phone' => false,
        'delivery_email' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'order_number' => 'order_number',
        'pickup_company' => 'pickup_company',
        'pickup_firstname' => 'pickup_firstname',
        'pickup_lastname' => 'pickup_lastname',
        'pickup_street' => 'pickup_street',
        'pickup_country' => 'pickup_country',
        'pickup_zip' => 'pickup_zip',
        'pickup_city' => 'pickup_city',
        'pickup_phone' => 'pickup_phone',
        'pickup_email' => 'pickup_email',
        'delivery_company' => 'delivery_company',
        'delivery_firstname' => 'delivery_firstname',
        'delivery_lastname' => 'delivery_lastname',
        'delivery_street' => 'delivery_street',
        'delivery_country' => 'delivery_country',
        'delivery_zip' => 'delivery_zip',
        'delivery_city' => 'delivery_city',
        'delivery_phone' => 'delivery_phone',
        'delivery_email' => 'delivery_email'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'order_number' => 'setOrderNumber',
        'pickup_company' => 'setPickupCompany',
        'pickup_firstname' => 'setPickupFirstname',
        'pickup_lastname' => 'setPickupLastname',
        'pickup_street' => 'setPickupStreet',
        'pickup_country' => 'setPickupCountry',
        'pickup_zip' => 'setPickupZip',
        'pickup_city' => 'setPickupCity',
        'pickup_phone' => 'setPickupPhone',
        'pickup_email' => 'setPickupEmail',
        'delivery_company' => 'setDeliveryCompany',
        'delivery_firstname' => 'setDeliveryFirstname',
        'delivery_lastname' => 'setDeliveryLastname',
        'delivery_street' => 'setDeliveryStreet',
        'delivery_country' => 'setDeliveryCountry',
        'delivery_zip' => 'setDeliveryZip',
        'delivery_city' => 'setDeliveryCity',
        'delivery_phone' => 'setDeliveryPhone',
        'delivery_email' => 'setDeliveryEmail'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'order_number' => 'getOrderNumber',
        'pickup_company' => 'getPickupCompany',
        'pickup_firstname' => 'getPickupFirstname',
        'pickup_lastname' => 'getPickupLastname',
        'pickup_street' => 'getPickupStreet',
        'pickup_country' => 'getPickupCountry',
        'pickup_zip' => 'getPickupZip',
        'pickup_city' => 'getPickupCity',
        'pickup_phone' => 'getPickupPhone',
        'pickup_email' => 'getPickupEmail',
        'delivery_company' => 'getDeliveryCompany',
        'delivery_firstname' => 'getDeliveryFirstname',
        'delivery_lastname' => 'getDeliveryLastname',
        'delivery_street' => 'getDeliveryStreet',
        'delivery_country' => 'getDeliveryCountry',
        'delivery_zip' => 'getDeliveryZip',
        'delivery_city' => 'getDeliveryCity',
        'delivery_phone' => 'getDeliveryPhone',
        'delivery_email' => 'getDeliveryEmail'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('order_number', $data ?? [], null);
        $this->setIfExists('pickup_company', $data ?? [], null);
        $this->setIfExists('pickup_firstname', $data ?? [], null);
        $this->setIfExists('pickup_lastname', $data ?? [], null);
        $this->setIfExists('pickup_street', $data ?? [], null);
        $this->setIfExists('pickup_country', $data ?? [], null);
        $this->setIfExists('pickup_zip', $data ?? [], null);
        $this->setIfExists('pickup_city', $data ?? [], null);
        $this->setIfExists('pickup_phone', $data ?? [], null);
        $this->setIfExists('pickup_email', $data ?? [], null);
        $this->setIfExists('delivery_company', $data ?? [], null);
        $this->setIfExists('delivery_firstname', $data ?? [], null);
        $this->setIfExists('delivery_lastname', $data ?? [], null);
        $this->setIfExists('delivery_street', $data ?? [], null);
        $this->setIfExists('delivery_country', $data ?? [], null);
        $this->setIfExists('delivery_zip', $data ?? [], null);
        $this->setIfExists('delivery_city', $data ?? [], null);
        $this->setIfExists('delivery_phone', $data ?? [], null);
        $this->setIfExists('delivery_email', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets order_number
     *
     * @return string|null
     */
    public function getOrderNumber()
    {
        return $this->container['order_number'];
    }

    /**
     * Sets order_number
     *
     * @param string|null $order_number Your order reference
     *
     * @return self
     */
    public function setOrderNumber($order_number)
    {
        if (is_null($order_number)) {
            throw new \InvalidArgumentException('non-nullable order_number cannot be null');
        }
        $this->container['order_number'] = $order_number;

        return $this;
    }

    /**
     * Gets pickup_company
     *
     * @return string|null
     */
    public function getPickupCompany()
    {
        return $this->container['pickup_company'];
    }

    /**
     * Sets pickup_company
     *
     * @param string|null $pickup_company Consignee Company Name
     *
     * @return self
     */
    public function setPickupCompany($pickup_company)
    {
        if (is_null($pickup_company)) {
            throw new \InvalidArgumentException('non-nullable pickup_company cannot be null');
        }
        $this->container['pickup_company'] = $pickup_company;

        return $this;
    }

    /**
     * Gets pickup_firstname
     *
     * @return string|null
     */
    public function getPickupFirstname()
    {
        return $this->container['pickup_firstname'];
    }

    /**
     * Sets pickup_firstname
     *
     * @param string|null $pickup_firstname Consignee First Name
     *
     * @return self
     */
    public function setPickupFirstname($pickup_firstname)
    {
        if (is_null($pickup_firstname)) {
            throw new \InvalidArgumentException('non-nullable pickup_firstname cannot be null');
        }
        $this->container['pickup_firstname'] = $pickup_firstname;

        return $this;
    }

    /**
     * Gets pickup_lastname
     *
     * @return string|null
     */
    public function getPickupLastname()
    {
        return $this->container['pickup_lastname'];
    }

    /**
     * Sets pickup_lastname
     *
     * @param string|null $pickup_lastname Consignee Last Name
     *
     * @return self
     */
    public function setPickupLastname($pickup_lastname)
    {
        if (is_null($pickup_lastname)) {
            throw new \InvalidArgumentException('non-nullable pickup_lastname cannot be null');
        }
        $this->container['pickup_lastname'] = $pickup_lastname;

        return $this;
    }

    /**
     * Gets pickup_street
     *
     * @return string|null
     */
    public function getPickupStreet()
    {
        return $this->container['pickup_street'];
    }

    /**
     * Sets pickup_street
     *
     * @param string|null $pickup_street Consignee Street
     *
     * @return self
     */
    public function setPickupStreet($pickup_street)
    {
        if (is_null($pickup_street)) {
            throw new \InvalidArgumentException('non-nullable pickup_street cannot be null');
        }
        $this->container['pickup_street'] = $pickup_street;

        return $this;
    }

    /**
     * Gets pickup_country
     *
     * @return string|null
     */
    public function getPickupCountry()
    {
        return $this->container['pickup_country'];
    }

    /**
     * Sets pickup_country
     *
     * @param string|null $pickup_country Consignee Country
     *
     * @return self
     */
    public function setPickupCountry($pickup_country)
    {
        if (is_null($pickup_country)) {
            throw new \InvalidArgumentException('non-nullable pickup_country cannot be null');
        }
        $this->container['pickup_country'] = $pickup_country;

        return $this;
    }

    /**
     * Gets pickup_zip
     *
     * @return string|null
     */
    public function getPickupZip()
    {
        return $this->container['pickup_zip'];
    }

    /**
     * Sets pickup_zip
     *
     * @param string|null $pickup_zip Consignee Zipcode
     *
     * @return self
     */
    public function setPickupZip($pickup_zip)
    {
        if (is_null($pickup_zip)) {
            throw new \InvalidArgumentException('non-nullable pickup_zip cannot be null');
        }
        $this->container['pickup_zip'] = $pickup_zip;

        return $this;
    }

    /**
     * Gets pickup_city
     *
     * @return string|null
     */
    public function getPickupCity()
    {
        return $this->container['pickup_city'];
    }

    /**
     * Sets pickup_city
     *
     * @param string|null $pickup_city Consignee City
     *
     * @return self
     */
    public function setPickupCity($pickup_city)
    {
        if (is_null($pickup_city)) {
            throw new \InvalidArgumentException('non-nullable pickup_city cannot be null');
        }
        $this->container['pickup_city'] = $pickup_city;

        return $this;
    }

    /**
     * Gets pickup_phone
     *
     * @return string|null
     */
    public function getPickupPhone()
    {
        return $this->container['pickup_phone'];
    }

    /**
     * Sets pickup_phone
     *
     * @param string|null $pickup_phone Consignee Phonenumber
     *
     * @return self
     */
    public function setPickupPhone($pickup_phone)
    {
        if (is_null($pickup_phone)) {
            throw new \InvalidArgumentException('non-nullable pickup_phone cannot be null');
        }
        $this->container['pickup_phone'] = $pickup_phone;

        return $this;
    }

    /**
     * Gets pickup_email
     *
     * @return string|null
     */
    public function getPickupEmail()
    {
        return $this->container['pickup_email'];
    }

    /**
     * Sets pickup_email
     *
     * @param string|null $pickup_email Consignee E-Mail
     *
     * @return self
     */
    public function setPickupEmail($pickup_email)
    {
        if (is_null($pickup_email)) {
            throw new \InvalidArgumentException('non-nullable pickup_email cannot be null');
        }
        $this->container['pickup_email'] = $pickup_email;

        return $this;
    }

    /**
     * Gets delivery_company
     *
     * @return string|null
     */
    public function getDeliveryCompany()
    {
        return $this->container['delivery_company'];
    }

    /**
     * Sets delivery_company
     *
     * @param string|null $delivery_company Recipient Company Name
     *
     * @return self
     */
    public function setDeliveryCompany($delivery_company)
    {
        if (is_null($delivery_company)) {
            throw new \InvalidArgumentException('non-nullable delivery_company cannot be null');
        }
        $this->container['delivery_company'] = $delivery_company;

        return $this;
    }

    /**
     * Gets delivery_firstname
     *
     * @return string|null
     */
    public function getDeliveryFirstname()
    {
        return $this->container['delivery_firstname'];
    }

    /**
     * Sets delivery_firstname
     *
     * @param string|null $delivery_firstname Recipient First Name
     *
     * @return self
     */
    public function setDeliveryFirstname($delivery_firstname)
    {
        if (is_null($delivery_firstname)) {
            throw new \InvalidArgumentException('non-nullable delivery_firstname cannot be null');
        }
        $this->container['delivery_firstname'] = $delivery_firstname;

        return $this;
    }

    /**
     * Gets delivery_lastname
     *
     * @return string|null
     */
    public function getDeliveryLastname()
    {
        return $this->container['delivery_lastname'];
    }

    /**
     * Sets delivery_lastname
     *
     * @param string|null $delivery_lastname Recipient Last Name
     *
     * @return self
     */
    public function setDeliveryLastname($delivery_lastname)
    {
        if (is_null($delivery_lastname)) {
            throw new \InvalidArgumentException('non-nullable delivery_lastname cannot be null');
        }
        $this->container['delivery_lastname'] = $delivery_lastname;

        return $this;
    }

    /**
     * Gets delivery_street
     *
     * @return string|null
     */
    public function getDeliveryStreet()
    {
        return $this->container['delivery_street'];
    }

    /**
     * Sets delivery_street
     *
     * @param string|null $delivery_street Recipient Street
     *
     * @return self
     */
    public function setDeliveryStreet($delivery_street)
    {
        if (is_null($delivery_street)) {
            throw new \InvalidArgumentException('non-nullable delivery_street cannot be null');
        }
        $this->container['delivery_street'] = $delivery_street;

        return $this;
    }

    /**
     * Gets delivery_country
     *
     * @return string|null
     */
    public function getDeliveryCountry()
    {
        return $this->container['delivery_country'];
    }

    /**
     * Sets delivery_country
     *
     * @param string|null $delivery_country Recipient Country
     *
     * @return self
     */
    public function setDeliveryCountry($delivery_country)
    {
        if (is_null($delivery_country)) {
            throw new \InvalidArgumentException('non-nullable delivery_country cannot be null');
        }
        $this->container['delivery_country'] = $delivery_country;

        return $this;
    }

    /**
     * Gets delivery_zip
     *
     * @return string|null
     */
    public function getDeliveryZip()
    {
        return $this->container['delivery_zip'];
    }

    /**
     * Sets delivery_zip
     *
     * @param string|null $delivery_zip Recipient Zipcode
     *
     * @return self
     */
    public function setDeliveryZip($delivery_zip)
    {
        if (is_null($delivery_zip)) {
            throw new \InvalidArgumentException('non-nullable delivery_zip cannot be null');
        }
        $this->container['delivery_zip'] = $delivery_zip;

        return $this;
    }

    /**
     * Gets delivery_city
     *
     * @return string|null
     */
    public function getDeliveryCity()
    {
        return $this->container['delivery_city'];
    }

    /**
     * Sets delivery_city
     *
     * @param string|null $delivery_city Recipient City
     *
     * @return self
     */
    public function setDeliveryCity($delivery_city)
    {
        if (is_null($delivery_city)) {
            throw new \InvalidArgumentException('non-nullable delivery_city cannot be null');
        }
        $this->container['delivery_city'] = $delivery_city;

        return $this;
    }

    /**
     * Gets delivery_phone
     *
     * @return string|null
     */
    public function getDeliveryPhone()
    {
        return $this->container['delivery_phone'];
    }

    /**
     * Sets delivery_phone
     *
     * @param string|null $delivery_phone Recipient Phonenumber
     *
     * @return self
     */
    public function setDeliveryPhone($delivery_phone)
    {
        if (is_null($delivery_phone)) {
            throw new \InvalidArgumentException('non-nullable delivery_phone cannot be null');
        }
        $this->container['delivery_phone'] = $delivery_phone;

        return $this;
    }

    /**
     * Gets delivery_email
     *
     * @return string|null
     */
    public function getDeliveryEmail()
    {
        return $this->container['delivery_email'];
    }

    /**
     * Sets delivery_email
     *
     * @param string|null $delivery_email Recipient E-Mail
     *
     * @return self
     */
    public function setDeliveryEmail($delivery_email)
    {
        if (is_null($delivery_email)) {
            throw new \InvalidArgumentException('non-nullable delivery_email cannot be null');
        }
        $this->container['delivery_email'] = $delivery_email;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


