<?php
/**
 * Parcel
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\cargoInternational
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spedition.de - Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\cargoInternational\Model;

use \ArrayAccess;
use \kruegge82\cargoInternational\ObjectSerializer;

/**
 * Parcel Class Doc Comment
 *
 * @category Class
 * @package  kruegge82\cargoInternational
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Parcel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Parcel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'kind' => 'string',
        'quantity' => 'int',
        'description' => 'string',
        'weight_kg' => 'float',
        'length_cm' => 'float',
        'width_cm' => 'float',
        'height_cm' => 'float',
        'value_eur' => 'float',
        'stackable' => 'bool',
        'hazardous' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'kind' => null,
        'quantity' => 'int32',
        'description' => null,
        'weight_kg' => 'float',
        'length_cm' => 'float',
        'width_cm' => 'float',
        'height_cm' => 'float',
        'value_eur' => 'float',
        'stackable' => null,
        'hazardous' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'kind' => false,
        'quantity' => false,
        'description' => false,
        'weight_kg' => false,
        'length_cm' => false,
        'width_cm' => false,
        'height_cm' => false,
        'value_eur' => false,
        'stackable' => false,
        'hazardous' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kind' => 'kind',
        'quantity' => 'quantity',
        'description' => 'description',
        'weight_kg' => 'weight_kg',
        'length_cm' => 'length_cm',
        'width_cm' => 'width_cm',
        'height_cm' => 'height_cm',
        'value_eur' => 'value_eur',
        'stackable' => 'stackable',
        'hazardous' => 'hazardous'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kind' => 'setKind',
        'quantity' => 'setQuantity',
        'description' => 'setDescription',
        'weight_kg' => 'setWeightKg',
        'length_cm' => 'setLengthCm',
        'width_cm' => 'setWidthCm',
        'height_cm' => 'setHeightCm',
        'value_eur' => 'setValueEur',
        'stackable' => 'setStackable',
        'hazardous' => 'setHazardous'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kind' => 'getKind',
        'quantity' => 'getQuantity',
        'description' => 'getDescription',
        'weight_kg' => 'getWeightKg',
        'length_cm' => 'getLengthCm',
        'width_cm' => 'getWidthCm',
        'height_cm' => 'getHeightCm',
        'value_eur' => 'getValueEur',
        'stackable' => 'getStackable',
        'hazardous' => 'getHazardous'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const KIND_PARCEL = 'parcel';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getKindAllowableValues()
    {
        return [
            self::KIND_PARCEL,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('kind', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], 1);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('weight_kg', $data ?? [], null);
        $this->setIfExists('length_cm', $data ?? [], null);
        $this->setIfExists('width_cm', $data ?? [], null);
        $this->setIfExists('height_cm', $data ?? [], null);
        $this->setIfExists('value_eur', $data ?? [], null);
        $this->setIfExists('stackable', $data ?? [], null);
        $this->setIfExists('hazardous', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['kind'] === null) {
            $invalidProperties[] = "'kind' can't be null";
        }
        $allowedValues = $this->getKindAllowableValues();
        if (!is_null($this->container['kind']) && !in_array($this->container['kind'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'kind', must be one of '%s'",
                $this->container['kind'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if (($this->container['quantity'] < 1)) {
            $invalidProperties[] = "invalid value for 'quantity', must be bigger than or equal to 1.";
        }

        if ($this->container['weight_kg'] === null) {
            $invalidProperties[] = "'weight_kg' can't be null";
        }
        if (($this->container['weight_kg'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'weight_kg', must be bigger than or equal to 0.0.";
        }

        if ($this->container['length_cm'] === null) {
            $invalidProperties[] = "'length_cm' can't be null";
        }
        if (($this->container['length_cm'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'length_cm', must be bigger than or equal to 0.0.";
        }

        if ($this->container['width_cm'] === null) {
            $invalidProperties[] = "'width_cm' can't be null";
        }
        if (($this->container['width_cm'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'width_cm', must be bigger than or equal to 0.0.";
        }

        if ($this->container['height_cm'] === null) {
            $invalidProperties[] = "'height_cm' can't be null";
        }
        if (($this->container['height_cm'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'height_cm', must be bigger than or equal to 0.0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kind
     *
     * @return string
     */
    public function getKind()
    {
        return $this->container['kind'];
    }

    /**
     * Sets kind
     *
     * @param string $kind kind
     *
     * @return self
     */
    public function setKind($kind)
    {
        if (is_null($kind)) {
            throw new \InvalidArgumentException('non-nullable kind cannot be null');
        }
        $allowedValues = $this->getKindAllowableValues();
        if (!in_array($kind, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'kind', must be one of '%s'",
                    $kind,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['kind'] = $kind;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return int
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param int $quantity Number of identical parcels of this type
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }

        if (($quantity < 1)) {
            throw new \InvalidArgumentException('invalid value for $quantity when calling Parcel., must be bigger than or equal to 1.');
        }

        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Goods description / contents
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets weight_kg
     *
     * @return float
     */
    public function getWeightKg()
    {
        return $this->container['weight_kg'];
    }

    /**
     * Sets weight_kg
     *
     * @param float $weight_kg Weight per item in kilograms
     *
     * @return self
     */
    public function setWeightKg($weight_kg)
    {
        if (is_null($weight_kg)) {
            throw new \InvalidArgumentException('non-nullable weight_kg cannot be null');
        }

        if (($weight_kg < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $weight_kg when calling Parcel., must be bigger than or equal to 0.0.');
        }

        $this->container['weight_kg'] = $weight_kg;

        return $this;
    }

    /**
     * Gets length_cm
     *
     * @return float
     */
    public function getLengthCm()
    {
        return $this->container['length_cm'];
    }

    /**
     * Sets length_cm
     *
     * @param float $length_cm length_cm
     *
     * @return self
     */
    public function setLengthCm($length_cm)
    {
        if (is_null($length_cm)) {
            throw new \InvalidArgumentException('non-nullable length_cm cannot be null');
        }

        if (($length_cm < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $length_cm when calling Parcel., must be bigger than or equal to 0.0.');
        }

        $this->container['length_cm'] = $length_cm;

        return $this;
    }

    /**
     * Gets width_cm
     *
     * @return float
     */
    public function getWidthCm()
    {
        return $this->container['width_cm'];
    }

    /**
     * Sets width_cm
     *
     * @param float $width_cm width_cm
     *
     * @return self
     */
    public function setWidthCm($width_cm)
    {
        if (is_null($width_cm)) {
            throw new \InvalidArgumentException('non-nullable width_cm cannot be null');
        }

        if (($width_cm < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $width_cm when calling Parcel., must be bigger than or equal to 0.0.');
        }

        $this->container['width_cm'] = $width_cm;

        return $this;
    }

    /**
     * Gets height_cm
     *
     * @return float
     */
    public function getHeightCm()
    {
        return $this->container['height_cm'];
    }

    /**
     * Sets height_cm
     *
     * @param float $height_cm height_cm
     *
     * @return self
     */
    public function setHeightCm($height_cm)
    {
        if (is_null($height_cm)) {
            throw new \InvalidArgumentException('non-nullable height_cm cannot be null');
        }

        if (($height_cm < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $height_cm when calling Parcel., must be bigger than or equal to 0.0.');
        }

        $this->container['height_cm'] = $height_cm;

        return $this;
    }

    /**
     * Gets value_eur
     *
     * @return float|null
     */
    public function getValueEur()
    {
        return $this->container['value_eur'];
    }

    /**
     * Sets value_eur
     *
     * @param float|null $value_eur Declared value per item in EUR
     *
     * @return self
     */
    public function setValueEur($value_eur)
    {
        if (is_null($value_eur)) {
            throw new \InvalidArgumentException('non-nullable value_eur cannot be null');
        }
        $this->container['value_eur'] = $value_eur;

        return $this;
    }

    /**
     * Gets stackable
     *
     * @return bool|null
     */
    public function getStackable()
    {
        return $this->container['stackable'];
    }

    /**
     * Sets stackable
     *
     * @param bool|null $stackable Whether items can be stacked
     *
     * @return self
     */
    public function setStackable($stackable)
    {
        if (is_null($stackable)) {
            throw new \InvalidArgumentException('non-nullable stackable cannot be null');
        }
        $this->container['stackable'] = $stackable;

        return $this;
    }

    /**
     * Gets hazardous
     *
     * @return bool|null
     */
    public function getHazardous()
    {
        return $this->container['hazardous'];
    }

    /**
     * Sets hazardous
     *
     * @param bool|null $hazardous DG indicator if applicable
     *
     * @return self
     */
    public function setHazardous($hazardous)
    {
        if (is_null($hazardous)) {
            throw new \InvalidArgumentException('non-nullable hazardous cannot be null');
        }
        $this->container['hazardous'] = $hazardous;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


